//! `aura init {kind}` and `aura add {type} "{name}"` — scaffolding commands.
//!
//! Generates the new `name.aura`-based project structure.
//!
//! # Root `name.aura`
//!
//! The project entry point. Replaces the old `namespace.aura` + ID-named
//! manifest. Combines the schema (`name::` block with `id`, `slug`, etc.),
//! manifest (`manifest::` block), and exports (`exports::` block).
//!
//! # Sub-folder `name.aura`
//!
//! Acts as a folder index. Contains a `name::` block (with `folder ->`)
//! and a `contains::` block listing all IDs in that folder.

use crate::directives::Kind;
use crate::error::{CompileError, Result};
use crate::logs::Logger;
use aura::id::{IdGen, Prefix};
use std::fs;
use std::path::{Path, PathBuf};

/// Options for `aura init`.
#[derive(Debug)]
pub struct InitOpts {
  pub kind: String,
  pub name: Option<String>,
  pub lang: Option<String>,
  pub dir: Option<PathBuf>,
}

/// Scaffolds a new AURA project.
pub fn init(opts: &InitOpts) -> Result<()> {
  let log = Logger::new();
  let kind = Kind::from_str(&opts.kind)
    .ok_or_else(|| CompileError::msg(format!("unknown kind `{}`", opts.kind)))?;

  let base = opts
    .dir
    .clone()
    .unwrap_or_else(|| PathBuf::from(kind_to_folder(&kind)));

  let name = opts.name.as_deref().unwrap_or("Untitled");
  let lang = opts.lang.as_deref().unwrap_or("en-US");

  // Create all standard directories.
  let dirs = standard_dirs(&kind);
  for dir in dirs {
    fs::create_dir_all(base.join(dir))
      .map_err(|e| CompileError::msg(format!("cannot create `{}`: {}", dir, e)))?;
  }

  let mut gen = IdGen::new();
  let root_id = gen.generate(kind_to_prefix(&kind));
  let person_id = gen.generate(Prefix::Person);
  let ann_id = gen.generate(Prefix::Person);

  // ---------------------------------------------------------------- //
  // Root name.aura — project entry point
  // Replaces: old namespace.aura + old {id}.aura manifest
  // ---------------------------------------------------------------- //

  let content_exports = content_export_lines(&kind);
  let tracks_members = initial_tracks_block(&kind);

  let root_name_content = format!(
    "## {name} — project entry point\n\
     ## Generated by `aura init {kind}`\n\
     \n\
     name::\n\
     \x20 id        -> {root_id}\n\
     \x20 root      -> https://hami.aduki.org/aura/1.0\n\
     \x20 kind      -> {kind}\n\
     \x20 slug      -> {slug}\n\
     \x20 lang      -> {lang}\n\
     \x20 annotator -> @annotator/{ann_id}\n\
     \n\
     manifest::\n\
     \x20 name      ! -> \"{name}\"\n\
     \x20 creator   ! -> @person/{person_id}\n\
     \x20 version     -> 1.0.0\n\
     \x20 released    -> 0000-00-00\n\
     \x20 access    -> @access/open\n\
     {members_block}\
     \n\
     exports::\n\
     \x20 info      -> @info/metadata\n\
     \x20 people    -> @info/people\n\
     {exports}\n",
    name = name,
    kind = opts.kind,
    root_id = root_id,
    slug = slug(name),
    lang = lang,
    ann_id = ann_id,
    person_id = person_id,
    members_block = tracks_members,
    exports = content_exports,
  );
  write_file(&base.join("name.aura"), &root_name_content)?;

  // ---------------------------------------------------------------- //
  // info/ files
  // ---------------------------------------------------------------- //

  // info/name.aura — folder index
  write_file(
    &base.join("info").join("name.aura"),
    "name::\n\
     \x20 folder -> info\n\
     \n\
     ## Info folder index — managed by `aura add` and the toolchain.\n",
  )?;

  // info/metadata.aura — supplementary metadata for cross-referencing tools
  write_file(
    &base.join("info").join("metadata.aura"),
    &format!(
      "schema::\n\
       \x20 root    -> https://hami.aduki.org/aura/1.0\n\
       \x20 kind    -> metadata\n\
       \x20 lang    -> {lang}\n\
       \n\
       manifest::\n\
       \x20 name      ! -> \"{name}\"\n\
       \x20 creator   ! -> @person/{person_id}\n\
       \x20 version     -> 1.0.0\n\
       \x20 released    -> 0000-00-00\n",
      lang = lang,
      name = name,
      person_id = person_id,
    ),
  )?;

  write_file(
    &base.join("info").join("people.aura"),
    "people::\n\n\
     \x20 ## Add person nodes here using `aura generate person`\n\
     \x20 ## Example:\n\
     \x20 ## p4xt9k2::\n\
     \x20 ##   first  -> \"Ada\"\n\
     \x20 ##   last   -> \"Okonkwo\"\n\
     \x20 ##   kind   -> artist\n",
  )?;

  write_file(
    &base.join("info").join("annotators.aura"),
    &format!(
      "annotators::\n\n\
       \x20 {ann_id}::\n\
       \x20   name  -> \"Local System User\"\n\
       \x20   roles -> annotator | editor\n",
      ann_id = ann_id,
    ),
  )?;

  // ---------------------------------------------------------------- //
  // Per-content-subfolder name.aura files (folder index)
  // ---------------------------------------------------------------- //
  for (folder, item_type) in content_namespaces(&kind) {
    write_subfolder_name(&base.join(folder), folder, item_type)?;
  }

  // meta/ name.aura (vocabulary registry)
  if dirs.contains(&"meta") {
    write_file(
      &base.join("meta").join("name.aura"),
      "name::\n\
       \x20 folder -> meta\n\
       \n\
       ## Vocabulary files for this project.\n\
       ## Add genres.aura, roles.aura, moods.aura as needed.\n",
    )?;
  }

  // configs/ stubs
  write_file(
    &base.join("configs").join("stores.aura"),
    "stores::\n\n\
     \x20 primary::\n\
     \x20   uri  -> aura://store.hami.aduki.org/catalogs/PLACEHOLDER\n\
     \x20   kind -> aduki\n",
  )?;

  write_file(
    &base.join("configs").join("ignore.aura"),
    "ignore::\n\n\
     \x20 ## Extra paths to exclude from .history/ tracking:\n\
     \x20 ## - path/to/exclude\n",
  )?;

  log.success(&format!("Created {}", base.display()));
  log.info("  Entry point   : name.aura");
  log.info(&format!("  Project ID    : {}", root_id));
  log.info(&format!("  Annotator ID  : {}", ann_id));
  log.info(&format!("  Person ID     : {}", person_id));
  Ok(())
}

/// Adds a new content file to an existing project and registers it.
pub fn add(type_name: &str, label: &str, project: &Path) -> Result<()> {
  let log = Logger::new();
  let prefix = type_to_prefix(type_name)?;
  let mut gen = IdGen::new();
  let id = gen.generate(prefix);
  let folder = type_to_folder(type_name);
  let path = project.join(folder).join(format!("{}.aura", id));

  fs::create_dir_all(path.parent().unwrap())
    .map_err(|e| CompileError::msg(format!("cannot create {}: {}", folder, e)))?;

  write_file(
    &path,
    &format!(
      "## {type_name} — {id}\n\
       ## Generated by `aura add {type_name} \"{label}\"`\n\
       \n\
       schema::\n\
       \x20 root      -> https://hami.aduki.org/aura/1.0\n\
       \x20 kind      -> {kind}\n\
       \x20 lang      -> en-US\n\
       \n\
       manifest::\n\
       \x20 name ! -> \"{label}\"\n",
      type_name = type_name,
      id = id,
      label = label,
      kind = type_to_kind(type_name),
    ),
  )?;

  // Register in the subfolder name.aura contains:: block.
  register_in_name(&project.join(folder), &id.to_string(), label)?;

  log.success(&format!("Created {}", path.display()));
  log.info(&format!("  ID: {}", id));
  Ok(())
}

// -------------------------------------------------------------------- //
// Helpers

fn write_subfolder_name(dir: &Path, folder: &str, item_type: &str) -> Result<()> {
  let content = format!(
    "name::\n\
     \x20 folder -> {folder}\n\
     \n\
     contains::\n\
     \x20 ## Add entries here after running:  aura add {item_type} \"Name\"\n\
     \x20 ## Example:  {example_id} -> \"Example {label}\"\n",
    folder = folder,
    item_type = item_type,
    example_id = example_id_for(item_type),
    label = capitalize(item_type),
  );
  write_file(&dir.join("name.aura"), &content)
}

fn register_in_name(folder_dir: &Path, id: &str, label: &str) -> Result<()> {
  let ns_path = folder_dir.join("name.aura");
  if !ns_path.exists() {
    return Ok(()); // no name file — skip silently
  }
  let mut content = fs::read_to_string(&ns_path)
    .map_err(|e| CompileError::msg(format!("cannot read name.aura: {}", e)))?;
  let entry = format!("\x20 {} -> \"{}\"\n", id, label);
  content.push_str(&entry);
  fs::write(&ns_path, &content)
    .map_err(|e| CompileError::msg(format!("cannot update name.aura: {}", e)))
}

/// Returns the initial collection tracks block for the root name.aura.
fn initial_tracks_block(kind: &Kind) -> String {
  match kind {
    Kind::AudioMusic => {
      "\ntracks::\n  members::\n    ## Add tracks after running: aura add track \"Name\"\n"
        .to_string()
    }
    _ => String::new(),
  }
}

fn content_export_lines(kind: &Kind) -> String {
  let mut lines = String::new();
  for (folder, _) in content_namespaces(kind) {
    lines.push_str(&format!("\x20 {folder}  -> @{folder}/*\n", folder = folder));
  }
  lines
}

fn content_namespaces(kind: &Kind) -> &'static [(&'static str, &'static str)] {
  match kind {
    Kind::AudioMusic => &[("tracks", "track"), ("variants", "variant")],
    Kind::AudioPodcast => &[("seasons", "season"), ("variants", "variant")],
    Kind::AudioBook => &[("chapters", "chapter"), ("variants", "variant")],
    Kind::VideoMovie => &[
      ("acts", "act"),
      ("scenes", "scene"),
      ("variants", "variant"),
    ],
    Kind::VideoSeries => &[("seasons", "season"), ("variants", "variant")],
    Kind::VideoDoc => &[("scenes", "scene"), ("variants", "variant")],
    Kind::VideoMusic => &[
      ("scenes", "scene"),
      ("shots", "shot"),
      ("variants", "variant"),
    ],
    _ => &[("variants", "variant")],
  }
}

fn kind_to_folder(kind: &Kind) -> &'static str {
  match kind {
    Kind::AudioMusic | Kind::AudioBook | Kind::AudioLive => "album",
    Kind::AudioPodcast => "podcast",
    Kind::VideoMovie => "film",
    Kind::VideoSeries => "tv-series",
    Kind::VideoDoc => "documentary",
    Kind::VideoMusic => "music-video",
    _ => "project",
  }
}

fn kind_to_prefix(kind: &Kind) -> Prefix {
  match kind {
    Kind::AudioMusic => Prefix::Collection,
    Kind::AudioPodcast => Prefix::Podcast,
    Kind::VideoMovie => Prefix::Film,
    Kind::VideoSeries => Prefix::Series,
    Kind::VideoDoc => Prefix::Documentary,
    Kind::VideoMusic => Prefix::MusicVideo,
    _ => Prefix::Collection,
  }
}

fn standard_dirs(kind: &Kind) -> &'static [&'static str] {
  match kind {
    Kind::AudioMusic => &[
      "info", "meta", "tracks", "variants", "artwork", "stems", "configs", "dist",
    ],
    Kind::AudioPodcast => &[
      "info", "meta", "seasons", "variants", "artwork", "configs", "dist",
    ],
    Kind::AudioBook => &[
      "info", "meta", "chapters", "variants", "artwork", "configs", "dist",
    ],
    Kind::VideoMovie => &[
      "info", "meta", "acts", "scenes", "variants", "artwork", "configs", "dist",
    ],
    Kind::VideoSeries => &[
      "info", "meta", "seasons", "variants", "artwork", "configs", "dist",
    ],
    Kind::VideoDoc => &[
      "info", "meta", "scenes", "variants", "artwork", "configs", "dist",
    ],
    Kind::VideoMusic => &[
      "info", "meta", "scenes", "shots", "variants", "artwork", "configs", "dist",
    ],
    _ => &["info", "meta", "variants", "artwork", "configs", "dist"],
  }
}

fn type_to_prefix(t: &str) -> Result<Prefix> {
  match t {
    "track" => Ok(Prefix::Track),
    "episode" => Ok(Prefix::Episode),
    "scene" => Ok(Prefix::Film),
    "shot" => Ok(Prefix::Film),
    "act" => Ok(Prefix::Film),
    "chapter" => Ok(Prefix::Book),
    "season" => Ok(Prefix::Season),
    "variant" => Ok(Prefix::Variant),
    "person" => Ok(Prefix::Person),
    _ => Err(CompileError::msg(format!("unknown content type `{}`", t))),
  }
}

fn type_to_folder(t: &str) -> &'static str {
  match t {
    "track" => "tracks",
    "episode" => "episodes",
    "scene" => "scenes",
    "shot" => "shots",
    "act" => "acts",
    "chapter" => "chapters",
    "season" => "seasons",
    "variant" => "variants",
    "person" => "info",
    _ => "content",
  }
}

fn type_to_kind(t: &str) -> &'static str {
  match t {
    "track" => "audio::music",
    "episode" => "audio::podcast",
    "scene" | "shot" | "act" => "video::movie",
    "chapter" => "audio::audiobook",
    _ => "audio::music",
  }
}

fn example_id_for(item_type: &str) -> &'static str {
  match item_type {
    "track" => "t7xab3c",
    "episode" => "ep7xb3n",
    "scene" => "f2xb7np",
    "shot" => "f8nm3kr",
    "act" => "f3xk9rp",
    "chapter" => "b4xp2mn",
    "season" => "sn2kr9l",
    "variant" => "v3qr7st",
    _ => "x000000",
  }
}

fn capitalize(s: &str) -> String {
  let mut c = s.chars();
  match c.next() {
    None => String::new(),
    Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
  }
}

fn slug(s: &str) -> String {
  s.to_lowercase()
    .chars()
    .map(|c| if c.is_alphanumeric() { c } else { '-' })
    .collect()
}

fn write_file(path: &Path, content: &str) -> Result<()> {
  if let Some(parent) = path.parent() {
    fs::create_dir_all(parent)
      .map_err(|e| CompileError::msg(format!("cannot create directory: {}", e)))?;
  }
  fs::write(path, content)
    .map_err(|e| CompileError::msg(format!("cannot write `{}`: {}", path.display(), e)))
}
