//! `aura init {kind}` and `aura add {type} "{name}"` — scaffolding commands.
//!
//! `aura init` scaffolds a new AURA project with the correct folder
//! structure, base `.aura` manifests, and initial toolchain config.
//!
//! `aura add` adds a new content file (track, episode, scene, etc.) to
//! an existing project.

use crate::directives::Kind;
use crate::error::{CompileError, Result};
use aura::id::{IdGen, Prefix};
use std::fs;
use std::path::{Path, PathBuf};

/// Options for `aura init`.
#[derive(Debug)]
pub struct InitOpts {
  /// Media kind, e.g. `"audio::album"`, `"video::movie"`.
  pub kind: String,
  /// Human-readable project name, e.g. `"Signal Loss"`.
  pub name: Option<String>,
  /// Primary language tag, e.g. `"en-US"`.
  pub lang: Option<String>,
  /// Target directory (default: current working directory).
  pub dir: Option<PathBuf>,
}

/// Scaffolds a new AURA project.
pub fn init(opts: &InitOpts) -> Result<()> {
  let kind = Kind::from_str(&opts.kind)
    .ok_or_else(|| CompileError::msg(format!("unknown kind `{}`", opts.kind)))?;

  let base = opts.dir.clone().unwrap_or_else(|| {
    let folder = kind_to_folder(&kind);
    PathBuf::from(folder)
  });

  let name = opts.name.as_deref().unwrap_or("Untitled");
  let lang = opts.lang.as_deref().unwrap_or("en-US");

  // Create standard directories.
  for dir in standard_dirs(&kind) {
    fs::create_dir_all(base.join(dir))
      .map_err(|e| CompileError::msg(format!("cannot create `{}`: {}", dir, e)))?;
  }

  // Generate root IDs.
  let mut gen = IdGen::new();
  let root_id = gen.generate(kind_to_prefix(&kind));

  // Write `namespace.aura`.
  let ns_content = format!(
        "schema::\n  root      -> https://hami.aduki.org/aura/1.0\n  kind      -> {}\n  namespace -> {}\n  lang      -> {}\n\nexports::\n  info      -> @info/metadata\n  people    -> @info/people\n",
        opts.kind,
        slug(name),
        lang
    );
  write_file(&base.join("namespace.aura"), &ns_content)?;

  // Write `info/metadata.aura`.
  let person_id = gen.generate(Prefix::Person);
  let meta_content = format!(
        "schema::\n  root    -> https://hami.aduki.org/aura/1.0\n  kind    -> metadata\n  lang    -> {}\n\nmanifest::\n  name      ! -> \"{}\"\n  creator   ! -> @person/{}\n  version     -> 1.0.0\n  released    -> 0000-00-00\n",
        lang, name, person_id
    );
  write_file(&base.join("info").join("metadata.aura"), &meta_content)?;

  // Write `info/people.aura`.
  let people_content = "people::\n\n  ## Add person nodes here using `aura generate person`\n";
  write_file(&base.join("info").join("people.aura"), people_content)?;

  // Write `info/annotators.aura`.
  let ann_id = gen.generate(Prefix::Person);
  let ann_content = format!(
    "annotators::\n\n  {}::\n    name  -> \"Local System User\"\n    roles -> annotator | editor\n",
    ann_id
  );
  write_file(&base.join("info").join("annotators.aura"), &ann_content)?;

  // Write root manifest file (collection, film manifest, etc.)
  let manifest_content = format!(
        "## {} root manifest\n## Generated by `aura init {}`\n\nschema::\n  root      -> https://hami.aduki.org/aura/1.0\n  kind      -> {}\n  lang      -> {}\n  annotator -> @annotator/{}\n",
        name, opts.kind, opts.kind, lang, ann_id
    );
  write_file(&base.join(format!("{}.aura", root_id)), &manifest_content)?;

  // Write `configs/` stubs.
  write_file(&base.join("configs").join("stores.aura"), "stores::\n\n  primary::\n    uri  -> aura://store.hami.aduki.org/catalogs/PLACEHOLDER\n    kind -> aduki\n")?;
  write_file(
    &base.join("configs").join("ignore.aura"),
    "ignore::\n\n  ## Extra paths to exclude from .history/ tracking:\n  ## - path/to/exclude\n",
  )?;

  println!("Created {}", base.display());
  println!("  Root manifest: {}.aura", root_id);
  Ok(())
}

/// Adds a new content file to an existing project.
pub fn add(type_name: &str, label: &str, project: &Path) -> Result<()> {
  let prefix = type_to_prefix(type_name)?;
  let mut gen = IdGen::new();
  let id = gen.generate(prefix);
  let folder = type_to_folder(type_name);
  let path = project.join(&folder).join(format!("{}.aura", id));

  fs::create_dir_all(path.parent().unwrap())
    .map_err(|e| CompileError::msg(format!("cannot create {}: {}", folder, e)))?;

  let content = format!(
        "## {} — {}\n## Generated by `aura add {} \"{}\"`\n\nschema::\n  root      -> https://hami.aduki.org/aura/1.0\n  kind      -> {}\n  lang      -> en-US\n\nmanifest::\n  name ! -> \"{}\"\n",
        type_name, id, type_name, label, type_to_kind(type_name), label
    );
  write_file(&path, &content)?;

  println!("Created {}", path.display());
  Ok(())
}

// -------------------------------------------------------------------- //
// Internal helpers

fn kind_to_folder(kind: &Kind) -> &'static str {
  match kind {
    Kind::AudioMusic | Kind::AudioBook | Kind::AudioLive => "album",
    Kind::AudioPodcast => "podcast",
    Kind::VideoMovie => "film",
    Kind::VideoSeries => "tv-series",
    Kind::VideoDoc => "documentary",
    Kind::VideoMusic => "music-video",
    _ => "project",
  }
}

fn kind_to_prefix(kind: &Kind) -> Prefix {
  match kind {
    Kind::AudioMusic => Prefix::Collection,
    Kind::AudioPodcast => Prefix::Podcast,
    Kind::VideoMovie => Prefix::Film,
    Kind::VideoSeries => Prefix::Series,
    Kind::VideoDoc => Prefix::Documentary,
    Kind::VideoMusic => Prefix::MusicVideo,
    _ => Prefix::Collection,
  }
}

fn standard_dirs(kind: &Kind) -> &'static [&'static str] {
  match kind {
    Kind::AudioMusic => &[
      "info", "meta", "tracks", "variants", "artwork", "stems", "configs", "dist",
    ],
    Kind::AudioPodcast => &["info", "meta", "seasons", "artwork", "configs", "dist"],
    Kind::VideoMovie => &[
      "info", "meta", "acts", "scenes", "variants", "artwork", "configs", "dist",
    ],
    Kind::VideoMusic => &[
      "info", "meta", "scenes", "shots", "artwork", "configs", "dist",
    ],
    _ => &["info", "meta", "artwork", "configs", "dist"],
  }
}

fn type_to_prefix(t: &str) -> Result<Prefix> {
  match t {
    "track" => Ok(Prefix::Track),
    "episode" => Ok(Prefix::Episode),
    "scene" => Ok(Prefix::Film),
    "season" => Ok(Prefix::Season),
    "variant" => Ok(Prefix::Variant),
    "person" => Ok(Prefix::Person),
    _ => Err(CompileError::msg(format!("unknown content type `{}`", t))),
  }
}

fn type_to_folder(t: &str) -> &'static str {
  match t {
    "track" => "tracks",
    "episode" => "episodes",
    "scene" => "scenes",
    "season" => "seasons",
    "variant" => "variants",
    "person" => "info",
    _ => "content",
  }
}

fn type_to_kind(t: &str) -> &'static str {
  match t {
    "track" => "audio::music",
    "episode" => "audio::podcast",
    "scene" => "video::movie",
    _ => "audio::music",
  }
}

fn slug(s: &str) -> String {
  s.to_lowercase()
    .chars()
    .map(|c| if c.is_alphanumeric() { c } else { '-' })
    .collect()
}

fn write_file(path: &Path, content: &str) -> Result<()> {
  if let Some(parent) = path.parent() {
    fs::create_dir_all(parent)
      .map_err(|e| CompileError::msg(format!("cannot create directory: {}", e)))?;
  }
  fs::write(path, content)
    .map_err(|e| CompileError::msg(format!("cannot write `{}`: {}", path.display(), e)))
}
