//! HistoryNode — versioned take provenance compiled into `.atom`.
//!
//! When the compiler is invoked with `--embed-history`, `SourceDelta`
//! objects from `.history/` are translated into `HistoryNode` objects
//! (ATOM class `0x14`) and embedded in the interval tree. The engine
//! can then resolve `@history/v1.0::verse/one` queries at runtime.
//!
//! History resolution is always read-only. The working state changes
//! only via the toolchain (`aura take`, `aura rewind`, `aura mix`).
//!
//! History nodes are not authored in AURA directly — they are
//! generated by the compiler from the `.history/` object store.

use crate::person::StringRef;

/// A versioned take reference embedded in an `.atom` mesh.
///
/// ATOM class `0x14`. Only present when compiled with `--embed-history`.
/// Not in the working-draft `.atom` — only in archival builds.
#[repr(C)]
#[derive(Debug, Clone)]
pub struct HistoryNode {
  /// Take ID, e.g. `"tx3ab7k"`. Fixed 8 bytes with `tx` prefix.
  pub take_id: [u8; 8],
  /// Unix timestamp when this take was recorded.
  pub timestamp: u64,
  /// Stream this take belongs to → string pool.
  pub stream: StringRef,
  /// Optional mark name attached to this take → string pool.
  pub mark: Option<StringRef>,
  /// Optional human-readable message → string pool.
  pub message: Option<StringRef>,
  /// Byte offset into the ATOM mesh where the reconstructed content
  /// for this take begins. Set by the `hist::replay` pass.
  pub content_ptr: u32,
}
